name: First GitHub Action

on:
 push:
  branches:
    - main

jobs:
  first-job:
    run-on: ubuntu-latest
    
    steps:
       - name: Print Message
       run: echo "Hello first git hub action "

       - name: Print Date
       run: date
  
